In [1]:
import numpy as np

In [10]:
x=np.array(5)

In [11]:
x.shape

()

In [12]:
v = np.array([1,2,3,4])

In [13]:
v.shape #comma is there to show that it is a tuple

(4,)

In [17]:
v.reshape(1,4)

array([[1, 2, 3, 4]])

In [18]:
## reshape alternative 
x = v[None, :]

In [19]:
x
#Those lines create a slice that looks at all of the items of v but 
#asks NumPy to add a new dimension of size 1 for the associated axis.

array([[1, 2, 3, 4]])

In [20]:
#numpy opertaions
#scalar with numpy
v=[1,2,3,4,5]
x=np.array(v)+2
x

array([3, 4, 5, 6, 7])

In [21]:
#we can also use funs but using operations is better
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
a + b
#use above with same shape

array([[ 3,  7],
       [11, 15]])

In [39]:
#element wise multiplication
m = np.array([[1,2,3],[4,5,6]])
n = m * 5
m

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
n

array([[ 5, 10, 15],
       [20, 25, 30]])

In [31]:
m * n

array([[  5,  20,  45],
       [ 80, 125, 180]])

In [32]:
np.multiply(m, n)  

array([[  5,  20,  45],
       [ 80, 125, 180]])

In [51]:
#matrix multiplication
#must satisfy matrix rules
n=n.reshape(3,2)
c=np.matmul(m,n)
c

array([[110, 140],
       [245, 320]])

In [53]:
#np.dot can also be used but for 2-D matmul is preferable
d=np.dot(m,n)
d

array([[110, 140],
       [245, 320]])

In [54]:
#transpose can be used only when data is aranged in rows to make multiplication possible

#### A real use case of transpose

In [59]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])

In [61]:
inputs.shape

(1, 4)

In [64]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [65]:
weights.shape

(3, 4)

In [67]:
#here data is arranged in rows 
#so for multiplication transpose can be used
mul=np.matmul(inputs,weights.T)
mul

array([[-0.01299,  0.00664,  0.13494]])

In [69]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    min=inputs[0]
    for i in inputs:
        if i<min:
            min=i
    inputs_minus_min = input_array - min

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    
    
    inputs_div_max = inputs_minus_min/np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    s1=m1.shape
    s2=m2.shape
    if s1[1]!=s2[0] and s2[1]!=s1[0]:
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if s1[1]==s2[0]:
        return np.matmul(m1,m2)
        
    return np.matmul(m2,m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    x=sum(values)
    return x/len(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665


In [70]:
# Use the numpy library
import numpy as np


######################################################
#
#      MESSAGE TO STUDENTS:
#
#  This file contains a solution to the coding quiz. Feel free
#  to look at it when you are stuck, but try to solve the
#   problem on your own first.
#
######################################################


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    # We can use NumPy's min function and element-wise division
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    # We can use NumPy's max function and element-wise division
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # Check the shapes of the matrices m1 and m2. 
    # m1 and m2 will be ndarray objects.
    #
    # Return False if the shapes cannot be used for matrix
    # multiplication. You may not use a transpose
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:     
        return False

    # Have not returned False, so calculate the matrix product
    # of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)        
    else:
        return np.matmul(m2, m1)        


def find_mean(values):
    # Return the average of the values in the given Python list
    # NumPy has a lot of helpful methods like this.
    return np.mean(values)
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
